### ISSUE TITLE
Report the regression coverage 

### ISSUE THREAD

**Issue by muneebullashariff** [muneeb-mbytes/pulpino__spi_master__ip_verification#17]
Mention the coverage report:
- [x] Code coverage 
- [x] Functional coverage

**Comment by sahanapalesh** [comment]
Coverage report:

Code coverage :         **63.50%**
Functional coverage:  **28.76%**
![Capture_1](https://user-images.githubusercontent.com/91043932/156490782-7241a5b6-37dc-414e-9999-d92762f65d6f.png)

**Comment by Nadeem-Ahmed-S** [comment]
![remmina_screenshot-2022-3-16-12:12:50 178667](https://user-images.githubusercontent.com/91043967/158587500-d0521c45-effa-44ad-a32d-0f957fe0b090.png)

**Comment by Nadeem-Ahmed-S** [comment]
Coverage Report on 16-03-2022: 
 
-  Total Covergae : 59.20%
-  Code-coverage : 63.95%
-  Functional Coverage : 29.05%

![image](https://user-images.githubusercontent.com/91043967/158619175-c49b0edb-2921-4387-9c8d-f6a748c1681a.png)

**Comment by muneebullashariff** [comment]
This is a good metrics for the regression coverage. 
Closing this ticket.
